spring:
  application:
    name: plantory-discovery-service

server:
  port: 9761

eureka:
  client:
    register-with-eureka: false   # Eureka Server ??? Eureka? "?????"? ???? ??
    fetch-registry: false         # ?? Eureka Server(?? ?????) ??? ???? ??
